# Generated by Django 3.0 on 2020-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('moves', models.TextField()),
                ('winner', models.CharField(max_length=2)),
            ],
        ),
    ]
